### PR TITLE
Usage documentation for the css prop and the styled import

### PR DESCRIPTION
**Pull request by ben-rogerson**
~~Twin has fairly basic usage examples so I'm releasing some more advanced docs with usage examples of the **[css prop](https://github.com/ben-rogerson/twin.macro/blob/d25b984a6f713ed96173e29cd49992fd4d783e78/docs/css-prop-guide.md)** and the **[styled import](https://github.com/ben-rogerson/twin.macro/blob/d25b984a6f713ed96173e29cd49992fd4d783e78/docs/styled-import-guide.md)**.~~

~~Feel free to review, test and please let me know if I'm missing anything.~~

~~Update: I've decided these docs should really be on a twin documentation site rather than github - I'll leave them up here until the site is ready 👍~~ 

Update April 2021: I've re-written and released guides based on the work and responses in this branch:

- [The prop styling guide](https://github.com/ben-rogerson/twin.macro/blob/master/docs/prop-styling-guide.md)
- [Styled component guide](https://github.com/ben-rogerson/twin.macro/blob/master/docs/styled-component-guide.md)

### CODE REVIEW

**Comment by rattrayalex** [comment]
Some feedback on the css prop guide, from the perspective of someone shopping around on how they want to do styling on their next project (please don't take any of it too seriously, and please don't feel obligated to respond with anything more than a reacji! What you have is helpful as it is and doesn't require modifications IMO): 

1) I love the clean pros/cons comments!
2) I'm not sure the first use of `css` should have so many class names; it's a bit distracting.
3) Similarly, pulling the styles out into variables, objects, or reusing them in fancier ways seems like it might do better coming after the array/object examples, which helps motivate these examples.
4) Might be helpful to document any tradeoffs related to a `styles` function (eg; does it impact memoizability? does it help change the code later on?)
5) Similarly, are there tradeoffs to styles being declared inside the component vs outside?
6) Would be great to document whether you can use `tw` and `css` attributes together, eg; `tw="border" css={conditionalStyles}`, and whether that may or may not be a good idea.
7) I have to say, it's not clear to me why a template string would make the most sense when there are more styles?
8) The advantage of an object over an array doesn't seem motivated – maybe an example where an array outputs duplicative styles could help. 

For what it's worth, after reading this, I feel that I'd _probably_ try to standardize on this approach:

```js
<input css={[
  // always use an array
  // common styles first as `tw`
  tw`base styles`,
  // next up, simple tw conditionals, preferring booleans to ternaries
  isDark && tw`dark-styles`,
  isFocused && `focused-styles`,
  // last, anything complex or non-tw in an object
  {
    caretColor: '#123',
    '&::selection': tw`bg-purple-500`,
  }
]} />
```

and likely only pull out functions for specific tasks, like this:

```js
const buttonColor = ({ purpose }) => ({
  warning: 'yellow',
  danger: 'red',
  success: 'green'
}[purpose] || 'blue');
``` 
(which, come to think of it, is a pattern which might benefit from being documented in this guide as well).

**Comment by ben-rogerson** [comment]
Great feedback, thanks so much for your review.

It's great to hear you chose the array styling technique with booleans too - that's the same approach I use almost exclusively.

I'll definitely be taking all this on board in the next version.

Cheers 🍻

**Comment by neldeles** [comment]
Glad I stumbled upon this PR. Really love what Twin is doing but I must say looking for documentation for this was quite difficult. My biggest hurdle was trying to understand the best styling technique to apply. The few articles I read had different ways of writing the CSS-in-JS and I was unsure which was "best practice". These advanced docs helped greatly.

Feedback after going through it is I'd prefer having an opinionated styling technique outlined in the docs. Right now there are multiple ways documented, but it's not so clear when to use which style over the other. 

Personally, after a few hours of experimentation I've settled on trying out the following approach:

```js
import tw, { styled } from 'twin.macro'

const styles = {
  dark: tw`bg-black text-white border-white placeholder-gray-500 tracking-tight`,
}

const inputStyle = ({ isPrimary }) => [
  // Common base styles
  tw`rounded border`,
  // Conditional styles
  isPrimary && styles.dark,
  !isPrimary &&
    tw`bg-white text-black border-black placeholder-gray-700 tracking-wide`,
]

export default styled.input.attrs(props => ({
  placeholder: props.placeholder || 'empty placeholder',
}))(inputStyle)
```
It's a combination of the `styled` import and use within an array. This allows me to use `styled-component`'s `attrs` method so I can easily set default values for attributes. The use of the array for the styles is to avoid extra interpolation brackets. Thoughts on this approach?

**Comment by ben-rogerson** [comment]
@neldeles Your usage looks good to me - nice job.
Thanks for the feedback too, I've take it onboard and have released the following two guides:

- [The prop styling guide](https://github.com/ben-rogerson/twin.macro/blob/master/docs/prop-styling-guide.md)
- [Styled component guide](https://github.com/ben-rogerson/twin.macro/blob/master/docs/styled-component-guide.md)

**Pull request closed without merging**
