### PR TITLE
Add TwComponent to list of valid imports

### PR DESCRIPTION
**Pull request by MatthiasDunker**
Fix issue [#653](https://github.com/ben-rogerson/twin.macro/issues/653)

### CODE REVIEW

**Comment by ben-rogerson** [comment]
LGTM! It's going in.

Also, I'm looking to add the card example to the docs and I'm interested in  how you would approach avoiding the ts error here:

```js
import React from 'react'
import tw, { styled } from 'twin.macro'
import type { TwComponent } from 'twin.macro'
import type { StyledComponent } from '@emotion/styled'

interface CardInterface extends StyledComponent<{}> {
  Title: TwComponent<'h3'>
  Image: TwComponent<'div'>
  Text: TwComponent<'div'>
  Meta: TwComponent<'p'>
}

const Card = tw.div`` as CardInterface
Card.Title = styled.h3(({ isBig }: { isBig?: boolean }) => [
  isBig ? tw`text-lg` : tw`text-base`,
]) // < Card.Title error here
Card.Image = tw.div``
Card.Text = tw.div``
Card.Meta = tw.p``

const CardComponent = () => (
  <Card>
    <Card.Title>Title</Card.Title>
    <Card.Image>Image</Card.Image>
    <Card.Text>Text</Card.Text>
    <Card.Meta>Meta</Card.Meta>
  </Card>
)

export default CardComponent
```

```shell
Type 'StyledComponent<{ theme?: Theme | undefined; as?: ElementType<any> | undefined; } & { isBig?: boolean | undefined; }, DetailedHTMLProps<HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>, {}>' is not assignable to type 'TwComponent<"h3">'.
  Type 'ReactElement<any, any> | null' is not assignable to type 'Element'.
    Type 'null' is not assignable to type 'Element'.ts(2322)
```

**Comment by MatthiasDunker** [comment]
Thank you.
I will have a look into it!

**Comment by MatthiasDunker** [comment]
```typescript
interface CardInterface extends TwComponent<'div'> {
  Title: StyledComponent<{isBig?: boolean}>;
  Image: TwComponent<'div'>;
  Text: TwComponent<'div'>;
  Meta: TwComponent<'p'>;
}
```
For your case, I switched the types of the first and second line of the interface.
Does it solve your issue?

**Comment by ben-rogerson** [comment]
That looks like a good solution, we’ll add it to the examples during the next revision 👍

**Pull request merged**
