### PR TITLE
fix(typescript): typescript types

### LINKED ISSUE #77: Importing in Typescript errors ts(2614)
I finally started trying out twin (you recommended it on reddit a few weeks ago!) having issues starting up in typescript however.

I followed the installation guide for CRA, I've made two code sandboxes setting up:
Plain JS (Working): https://codesandbox.io/s/lucid-kapitsa-cjy3y?file=/src/App.js
TS (Errors): https://codesandbox.io/s/busy-moser-yxl7g?file=/src/App.tsx

As you can see the JS works fine, and the TS does display the elements styled but there is a TS error for the imports `Module '"../node_modules/twin.macro/types"' has no exported member 'tw'. Did you mean to use 'import tw from "../node_modules/twin.macro/types"' instead?ts(2614)` I'm assuming it can't find the type definitions? I know you say you've got them built in, not sure if I missed something in installation.

### PR DESCRIPTION
**Pull request by rbutera**
Fixes #77 

This one definitely isn't ready to be merged yet, need your help @kingdaro @ben-rogerson (and anyone in the community that can help with TypeScript!)

# Remaining problems to be resolved:

- [x] `styled` definiton
- [x] `css` prop definition
- [x] default and named export
- [x] `css` no-unused-vars compatibility

# styled and css prop definitions:

Pretty sure the way I've implemented support for `import {css, styled} from "twin.macro"` is **bad**:

```typescript
import emotionStyled from '@emotion/styled'
import { css as emotionCss } from '@emotion/core'
import styledComponents, { css as styledCss } from 'styled-components'

export declare const styled: typeof emotionStyled & typeof styledComponents
export declare const css: typeof emotionCss & typeof styledCss
```

# default and named export

supporting both `import {tw, styled} from "twin.macro"` (named export) and `import twin, { styled} from "twin.macro"` (default export) is problematic:

error when using default

We have three options as far as I can tell:

1. support only default export (like React)
2. support both, change recommended default export identifier (e.g. `twin`)
3. support both, become incompatible with `eslint-plugin-import`

I personally vote for either options 1 or 2 for maximum DX. I think option 1 is simplest!

Option 2 would require changing all of the documentation and may be confusing DX.

# `css` no-unused-vars compatibility

When using `css` from twin.macro then no-unused-vars gets triggered.

Maybe we should look at how babel-plugin-styled-components gets around this issue?

### CODE REVIEW

**Comment by rbutera** [comment]
PS: xo-react/space is quite necessary / recommended, not sure why this was removed @ben-rogerson ?

Fixes a lot of react/jsx specific listing issues, for example `no-unused-vars` when importing React

**Comment by zaguiini** [comment]
Couldn't we use [module augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html)?

**Comment by kingdaro** [comment]
A few thoughts

- I don't think the `styled`/`css` re-export from twin can be reasonably supported. The "correct" export depends on what's defined in the twin JSON config, which can't really be read from a .d.ts file.

  The method of exporting a "merged" type from both libraries would probably cause more issues than it's worth, if it even works at all to begin with.

  I think TS users are better off importing from the lib they use, which supports more than SC and emotion, and is a lot clearer anyway. Could maybe add a note in the docs about this.

- I don't think we should bend to the will of a linter rule. Users who use the import plugin should know themselves to use `twin`.

  As an aside, my typescript plugin would also need config to set the pragma used, it only supports and looks for `tw` at the moment, but that's on me

- Both of the above points I think applies to `css` triggering `no-unused-vars`. The twin reexports cause more issues than worth in TS land. I'm not sure I like the feature at all to begin with

**Comment by kingdaro** [comment]
> Can't we use [module augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html)?

I guess the _user_ could define their own exports, like
```ts
import 'twin.macro'
declare module 'twin.macro' {
  import styled, { css } from 'styled-components'
  export default styled
  export { css }
}
```
So maybe the best route for us would be to document this if TS users want the re-exports. But I still can't see it being a highly desired feature. Hardly saves much when everything's auto-imported anyway

**Comment by zaguiini** [comment]
> > Can't we use [module augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html)?
> 
> I guess the _user_ could define their own exports, like
> 
> ```ts
> import 'twin.macro'
> declare module 'twin.macro' {
>   import styled, { css } from 'styled-components'
>   export default styled
>   export { css }
> }
> ```
> 
> So maybe the best route for us would be to document this if TS users want the re-exports. But I still can't see it being a highly desired feature. Hardly saves much when everything's auto-imported anyway

Sorry, I replied in a rush. Yes, that's what I mean. To document the possibility of the user deciding it's typings for this case.

**Comment by rbutera** [comment]
I've just updated the PR as per your recommendations, guys, thank you very much @kingdaro @zaguiini 

Just to check, can you confirm the following works for module annotation?

## styled-components
```typescript
// twin.d.t.s
import 'twin.macro'
declare module 'twin.macro' {
  import styled, { css } from 'styled-components'
  export { css, styled }
}
```


## emotion
```typescript
// twin.d.t.s
import 'twin.macro'
declare module 'twin.macro' {
  import styled from '@emotion/styled'
  import { css } from '@emotion/core'
  export { css, styled }
}
```

I've also updated the documentation everywhere to reflect these changes.

Please have a look and let me know!

**Comment by kingdaro** [comment]
It works, but I needed to move the SC import outside the `declare module` block for it to work:
```ts
// twin.d.t.s
import "twin.macro"
import styled, { css } from "styled-components"
declare module "twin.macro" {
  export { css, styled }
}
```
The same will probably apply for emotion and others

**Comment by rbutera** [comment]
@kingdaro thanks, yeah I noticed that too

Turns out that when augmenting a module it's not permitted to export within the declaration so I've updated the docs to reflect that:

### for styled-components:

```typescript
// twin.d.t.s
import 'twin.macro' /* eslint-disable-line import/no-unassigned-import */
import styledComponent, { css as cssProperty } from 'styled-components'
declare module 'twin.macro' {
  const css: typeof cssProperty
  const styled: typeof styledComponent
}
```

### for emotion:

```typescript
// twin.d.t.s
import 'twin.macro'
import styledComponent from '@emotion/styled'
import { css as cssProperty } from '@emotion/core'
declare module 'twin.macro' {
  const css: typeof cssProperty
  const styled: typeof styledComponent
}
```

@ben-rogerson if kingdaro approves I think this is ready to be merged.

**NB:** this PR bumps the version number to 1.2.0 because the syntax is incompatible with 1.1.x

**Comment by rbutera** [comment]
Drafted the release for this (https://github.com/ben-rogerson/twin.macro/releases/tag/untagged-9b87f7fc1fe2b3d72212)

**Comment by flavio-ever** [comment]
I ended up defining this paleative solution `root\@types\twin.d.ts` 

```js
import 'twin.macro'
import styled, { css } from 'styled-components'
declare module 'twin.macro' {
  export { css, styled }
}
```

Any predictions to fix or update the documentation?

**Pull request merged**
