### PR TITLE
Backtick commenting

### PR DESCRIPTION
**Pull request by ben-rogerson**
This PR adds the ability to use both single and multiline comments within template literals.

Now you can use comments to disable classes temporarily or to document classes.

### Singleline comments

```js
tw`
// singleline comment
block
`;

// ↓ ↓ ↓ ↓ ↓ ↓

({
  "display": "block"
});
```

### Multiline comments

```js
tw`
/*
multiline comment
*/
flex`;

// ↓ ↓ ↓ ↓ ↓ ↓

({
  "display": "flex"
});
```

#### Notes

- Comments can only be used inside tw backticks (template literals)
- [VSCode Tailwind CSS IntelliSense](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss) doesn't recognise comments
- [VSCode Tailwind Twin IntelliSense](https://marketplace.visualstudio.com/items?itemName=lightyen.tailwindcss-intellisense-twin) supports comments (0.7.0+)

### CODE REVIEW

**Comment by ben-rogerson** [comment]
@lightyen Heads up - I'm adding commenting to twin

**Comment by lightyen** [comment]
Why not support comments in `data-tw` prop?

The following is valid syntax in javascript:
```js
let x = 0 // comment
let y = 1 /** comment */, z = 2
```

**Comment by ben-rogerson** [comment]
I've decided to leave the comments in the `data-tw` prop and instead opt for better formatting of the whitespace.

**Review by tannerlinsley — APPROVED** [review]

**Comment by lightyen** [comment]
I'm not familiar with testing, so I write some case in here:
```
// comment in variant group and consecutive strings
md:(text-xl/* text-yellow-500 */font-black)

// break right bracket
2xl:(// ####@@@@ )
background[/*start*/rgb(191, 201/*inner*/, 211)/*end*/])

// normal
relative
lg:(
    /***
    helloworld
    /****/
    //***
    flex
    text-5xl
    border-yellow-500
    /****/
)!
```
Expected result like this:
```
md:text-xl
md:font-black
2xl:background[rgb(191, 201, 211)]
relative
lg:flex!
lg:text-5xl!
lg:border-yellow-500!
```

**Comment by ben-rogerson** [comment]
@lightyen Thanks for those suggestions, I found and fixed some match issues.
I updated the regex for matching multiline comments [here](https://github.com/ben-rogerson/twin.macro/pull/341/commits/d937308420beeae5c29e518d69c5cc574a3491a9#diff-060641f8d67f2c85d3042ddbf123566cebc8c08a0337c4c543dfb8e691293386R45)

**Pull request merged**
